#Exploratory Data Analysis (EDA)
Exploratory Data Analysis (EDA) is the process of analyzing and summarizing a cleaned dataset to understand its patterns, distributions, relationships, and characteristics before building Machine Learning models.

###EDA helps us answer questions like:

- What does the data tell us?
- What patterns are present?
- Which variables are important?
- Are there any trends or relationships?

####Data Preprocessing
        
1. Understand the Business Problem
        
2. Understand the Dataset
        
3. Perform Descriptive Statistics
        
4. Analyze Individual Features (Univariate Analysis)
        
5. Analyze Relationships Between Features (Bivariate Analysis)
        
6. Analyze Multiple Features Together (Multivariate Analysis)
        
7. Detect Outliers
        
8. Create Visualizations
        
9. Draw Insights & Conclusions
        
10. Prepare Data for Machine Learning

#Example
EDA is like a doctor's initial health check-up before prescribing medicine.

1. The patient is the dataset.
2. The doctor is the data analyst.
3. The health check-up includes checking for missing values, duplicate records, data types, and summary statistics.
4. Only after understanding the "health" of the dataset do we proceed with visualization or machine learning.

#Outliers
An outlier is a value that is unusually high or unusually low compared to the rest of the data.

##Why Do Outliers Occur?

Outliers may occur because of:

1. Human data entry mistakes
2. Measurement errors
3. Experimental errors
4. Natural variations
5. Fraudulent activities

An outlier is a data value that is significantly different from the other values in the dataset.

Example:

25, 28, 30, 32, 35, 36, 38, 250

Here, 250 is an outlier because it is much larger than the other values.
Step 2: Arrange the Data

Before finding outliers, arrange the data in ascending order.

Example

10 15 18 20 22 24 26 30 35
Step 3: Calculate Quartiles

Quartiles divide the dataset into four equal parts.

Minimum

↓

Q1 (25%)

↓

Q2 (Median - 50%)

↓

Q3 (75%)

↓

Maximum
Q1 (First Quartile)
25% of the data lies below Q1.
Q2 (Median)
50% of the data lies below the median.
Q3 (Third Quartile)
75% of the data lies below Q3.
Step 4: Find the Quartiles

For a dataset arranged in ascending order:

10 15 18 20 22 24 26 30 35
Q1 = 18

Q2 = 22

Q3 = 30

(In Python, these are calculated automatically using the quantile() function.)

Step 5: Calculate IQR (Interquartile Range)
Formula
IQR = Q3 − Q1

Example

Q3 = 30

Q1 = 18

IQR = 30 − 18

IQR = 12
Step 6: Calculate the Lower Limit
Formula
Lower Limit = Q1 − (1.5 × IQR)

Example

Lower Limit = 18 − (1.5 × 12)

Lower Limit = 18 − 18

Lower Limit = 0
Step 7: Calculate the Upper Limit
Formula
Upper Limit = Q3 + (1.5 × IQR)

Example

Upper Limit = 30 + (1.5 × 12)

Upper Limit = 30 + 18

Upper Limit = 48
Step 8: Identify Outliers

Now compare every value in the dataset with the limits.

Rule
If Value < Lower Limit

OR

If Value > Upper Limit

↓

It is an Outlier

Example:

Lower Limit = 0

Upper Limit = 48

Dataset

10 15 18 20 22 24 26 30 35 250

Since

250 > 48

Therefore,

250 is an Outlier
Step 9: Handle Outliers

After detecting outliers, we can handle them using different methods.

Method 1

Remove the outlier.

Delete the row containing the outlier.
Method 2

Replace the outlier.

Replace with Mean

or

Replace with Median

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from google.colab import files

uploaded = files.upload()

Saving weight-height.csv to weight-height.csv

In [ ]:
import pandas as pd
df = pd.read_csv("heights (1).csv")
df

       name  height
0     mohan     1.2
1     maria     2.3
2     sakib     4.9
3       tao     5.1
4     virat     5.2
5    khusbu     5.4
6    dmitry     5.5
7    selena     5.5
8      john     5.6
9     imran     5.6
10     jose     5.8
11  deepika     5.9
12   yoseph     6.0
13    binod     6.1
14  gulshan     6.2
15  johnson     6.5
16   donald     7.1
17    aamir    14.5
18      ken    23.2
19      Liu    40.2

In [ ]:
df.describe()

          height
count  20.000000
mean    8.390000
std     8.782812
min     1.200000
25%     5.350000
50%     5.700000
75%     6.275000
max    40.200000

In [3]:
#Detect outliers using IQR
Q1 = df.height.quantile(0.25)
Q3 = df.height.quantile(0.75)
Q1, Q3

NameError: name 'df' is not defined

In [ ]:
IQR = Q3 - Q1
IQR

np.float64(0.9249999999999998)

In [ ]:
lower_limit = Q1 - 1.5*IQR
upper_limit = Q3 + 1.5*IQR
lower_limit, upper_limit

(np.float64(3.962500000000001), np.float64(7.6625))

In [ ]:
#Here are the outliers

df[(df.height<lower_limit)|(df.height>upper_limit)]

     name  height
0   mohan     1.2
1   maria     2.3
17  aamir    14.5
18    ken    23.2
19    Liu    40.2

In [ ]:
#Remove outliers
df_no_outlier = df[(df.height>lower_limit)&(df.height<upper_limit)]
df_no_outlier

       name  height
2     sakib     4.9
3       tao     5.1
4     virat     5.2
5    khusbu     5.4
6    dmitry     5.5
7    selena     5.5
8      john     5.6
9     imran     5.6
10     jose     5.8
11  deepika     5.9
12   yoseph     6.0
13    binod     6.1
14  gulshan     6.2
15  johnson     6.5
16   donald     7.1

#Task:
You are given height_weight.csv file which contains heights and weights of 1000 people. Dataset is taken from here, https://www.kaggle.com/mustafaali96/weight-height

You need to do this,

(1) Load this csv in pandas dataframe and first plot histograms for height and weight parameters

(2) Using IQR detect weight outliers and print them

(3) Using IQR, detect height outliers and print them

(4) replace the outliers with mean and median  and print the dataset